value:
  - server: localhost
    port: 1414
    messageDetailsList:
      - destinationName: DEV.QUEUE.1
        messages:
          - "\r\n\x01QP BARXTXS\r\n.HDQRMJU 281440/160B99PSA\r\n\x02AVS\r\nJU0580L30AUG LA BEGBCN\r\n\r\n\x03"
  - server: localhost
    port: 4141
    errors:
      - message: Server localhost(1414) is not pre-configured to be listened to.
